<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="1.3.2" name="base1" tilewidth="32" tileheight="32" tilecount="667" columns="23">
 <editorsettings>
  <export target="projects/mmo/cos/cos.map/src/main/resources" format=""/>
 </editorsettings>
 <image source="projects/mmo/resources/map1.png" trans="ff00ff" width="736" height="928"/>
 <tile id="23" type="GRASS"/>
 <tile id="24" type="GRASS"/>
 <tile id="25" type="GRASS"/>
 <tile id="26" type="WALL"/>
 <tile id="27" type="WALL"/>
 <tile id="28" type="Gate"/>
 <tile id="29" type="Gate"/>
 <tile id="30" type="GRASS"/>
 <tile id="31" type="GRASS"/>
 <tile id="32" type="GRASS"/>
 <tile id="33" type="GRASS"/>
 <tile id="46" type="GRASS"/>
 <tile id="47" type="GRASS"/>
 <tile id="48" type="GRASS"/>
 <tile id="49" type="WALL"/>
 <tile id="50" type="WALL"/>
 <tile id="51" type="Gate"/>
 <tile id="52" type="Gate"/>
 <tile id="53" type="GRASS"/>
 <tile id="54" type="GRASS"/>
 <tile id="55" type="GRASS"/>
 <tile id="56" type="GRASS"/>
 <tile id="69" type="GRASS"/>
 <tile id="70" type="GRASS"/>
 <tile id="71" type="GRASS"/>
 <tile id="72" type="WALL"/>
 <tile id="73" type="WALL"/>
 <tile id="74" type="WALL"/>
 <tile id="75" type="Gate"/>
 <tile id="76" type="GRASS"/>
 <tile id="77" type="GRASS"/>
 <tile id="78" type="GRASS"/>
 <tile id="92" type="GRASS"/>
 <tile id="93" type="GRASS"/>
 <tile id="94" type="GRASS"/>
 <tile id="95" type="WALL"/>
 <tile id="96" type="WALL"/>
 <tile id="97" type="WALL"/>
 <tile id="98" type="Gate"/>
 <tile id="115" type="GRASS"/>
 <tile id="116" type="GRASS"/>
 <tile id="117" type="GRASS"/>
 <tile id="118" type="GRASS"/>
 <tile id="119" type="GRASS"/>
 <tile id="120" type="GRASS"/>
 <tile id="121" type="GRASS"/>
 <tile id="122" type="GRASS"/>
 <tile id="123" type="GRASS"/>
 <tile id="124" type="GRASS"/>
 <tile id="125" type="GRASS"/>
 <tile id="139" type="GRASS"/>
 <tile id="141" type="GRASS"/>
 <tile id="142" type="GRASS"/>
 <tile id="143" type="GRASS"/>
 <tile id="144" type="GRASS"/>
 <tile id="145" type="GRASS"/>
 <tile id="146" type="GRASS"/>
 <tile id="147" type="GRASS"/>
 <tile id="148" type="GRASS"/>
 <tile id="164" type="GRASS"/>
 <tile id="165" type="GRASS"/>
 <tile id="166" type="GRASS"/>
 <tile id="167" type="GRASS"/>
 <tile id="168" type="GRASS"/>
 <tile id="169" type="GRASS"/>
 <tile id="170" type="GRASS"/>
 <tile id="171" type="GRASS"/>
 <tile id="187" type="GRASS"/>
 <tile id="188" type="GRASS"/>
 <tile id="189" type="GRASS"/>
 <tile id="190" type="GRASS"/>
 <tile id="191" type="GRASS"/>
 <tile id="192" type="GRASS"/>
 <tile id="193" type="GRASS"/>
 <tile id="194" type="GRASS"/>
 <tile id="199" type="WALL"/>
 <tile id="200" type="WALL"/>
 <tile id="201" type="Gate"/>
 <tile id="202" type="Gate"/>
 <tile id="210" type="GRASS"/>
 <tile id="211" type="GRASS"/>
 <tile id="212" type="GRASS"/>
 <tile id="213" type="GRASS"/>
 <tile id="214" type="GRASS"/>
 <tile id="215" type="GRASS"/>
 <tile id="216" type="GRASS"/>
 <tile id="217" type="GRASS"/>
 <tile id="222" type="WALL"/>
 <tile id="223" type="WALL"/>
 <tile id="224" type="Gate"/>
 <tile id="225" type="Gate"/>
 <tile id="226" type="WALL"/>
 <tile id="227" type="WALL"/>
 <tile id="228" type="WALL"/>
 <tile id="229" type="WALL"/>
 <tile id="234" type="GRASS"/>
 <tile id="236" type="GRASS"/>
 <tile id="237" type="GRASS"/>
 <tile id="238" type="GRASS"/>
 <tile id="239" type="GRASS"/>
 <tile id="240" type="GRASS"/>
 <tile id="245" type="WALL"/>
 <tile id="246" type="WALL"/>
 <tile id="247" type="WALL"/>
 <tile id="248" type="WALL"/>
 <tile id="249" type="WALL"/>
 <tile id="250" type="WALL"/>
 <tile id="251" type="WALL"/>
 <tile id="252" type="WALL"/>
 <tile id="258" type="GRASS"/>
 <tile id="259" type="GRASS"/>
 <tile id="260" type="GRASS"/>
 <tile id="261" type="GRASS"/>
 <tile id="262" type="GRASS"/>
 <tile id="263" type="GRASS"/>
 <tile id="268" type="WALL"/>
 <tile id="269" type="WALL"/>
 <tile id="270" type="WALL"/>
 <tile id="271" type="WALL"/>
 <tile id="281" type="GRASS"/>
 <tile id="282" type="GRASS"/>
 <tile id="283" type="GRASS"/>
 <tile id="284" type="GRASS"/>
 <tile id="285" type="GRASS"/>
 <tile id="286" type="GRASS"/>
 <tile id="304" type="GRASS"/>
 <tile id="305" type="GRASS"/>
 <tile id="306" type="GRASS"/>
 <tile id="307" type="GRASS"/>
 <tile id="308" type="GRASS"/>
 <tile id="309" type="GRASS"/>
 <tile id="327" type="GRASS"/>
 <tile id="328" type="GRASS"/>
 <tile id="329" type="GRASS"/>
 <tile id="330" type="GRASS"/>
 <tile id="331" type="GRASS"/>
 <tile id="332" type="GRASS"/>
 <tile id="368" type="SHALLOW"/>
 <tile id="369" type="SHALLOW"/>
 <tile id="370" type="SHALLOW"/>
 <tile id="371" type="SHALLOW"/>
 <tile id="374" type="SHALLOW"/>
 <tile id="375" type="SHALLOW"/>
 <tile id="376" type="SHALLOW"/>
 <tile id="391" type="SHALLOW"/>
 <tile id="392" type="SHALLOW"/>
 <tile id="393" type="GRASS"/>
 <tile id="394" type="GRASS"/>
 <tile id="395" type="GRASS"/>
 <tile id="396" type="GRASS"/>
 <tile id="397" type="SHALLOW"/>
 <tile id="398" type="SHALLOW"/>
 <tile id="399" type="SHALLOW"/>
 <tile id="414" type="SHALLOW"/>
 <tile id="415" type="SHALLOW"/>
 <tile id="416" type="GRASS"/>
 <tile id="417" type="GRASS"/>
 <tile id="418" type="GRASS"/>
 <tile id="419" type="GRASS"/>
 <tile id="420" type="SHALLOW"/>
 <tile id="421" type="SHALLOW"/>
 <tile id="422" type="SHALLOW"/>
 <tile id="437" type="SHALLOW"/>
 <tile id="438" type="SHALLOW"/>
 <tile id="439" type="SHALLOW"/>
 <tile id="440" type="SHALLOW"/>
 <tile id="441" type="DEEP_WATER"/>
 <tile id="442" type="DEEP_WATER"/>
 <tile id="443" type="GRASS"/>
 <tile id="444" type="GRASS"/>
 <tile id="445" type="GRASS"/>
 <tile id="451" type="DEEP_WATER"/>
 <tile id="452" type="DEEP_WATER"/>
 <tile id="460" type="SHALLOW"/>
 <tile id="461" type="SHALLOW"/>
 <tile id="462" type="SHALLOW"/>
 <tile id="463" type="SHALLOW"/>
 <tile id="464" type="DEEP_WATER"/>
 <tile id="465" type="DEEP_WATER"/>
 <tile id="466" type="GRASS"/>
 <tile id="467" type="GRASS"/>
 <tile id="468" type="GRASS"/>
 <tile id="474" type="DEEP_WATER"/>
 <tile id="475" type="DEEP_WATER"/>
 <tile id="485" type="SHALLOW"/>
 <tile id="486" type="SHALLOW"/>
 <tile id="487" type="DEEP_WATER"/>
 <tile id="488" type="DEEP_WATER"/>
 <tile id="489" type="GRASS"/>
 <tile id="490" type="GRASS"/>
 <tile id="491" type="GRASS"/>
 <tile id="497" type="DEEP_WATER"/>
 <tile id="498" type="DEEP_WATER"/>
 <tile id="506" type="GRASS"/>
 <tile id="507" type="GRASS"/>
 <tile id="508" type="GRASS"/>
 <tile id="509" type="GRASS"/>
 <tile id="510" type="GRASS"/>
 <tile id="511" type="GRASS"/>
 <tile id="512" type="GRASS"/>
 <tile id="513" type="GRASS"/>
 <tile id="514" type="GRASS"/>
 <tile id="529" type="GRASS"/>
 <tile id="530" type="GRASS"/>
 <tile id="531" type="GRASS"/>
 <tile id="532" type="GRASS"/>
 <tile id="533" type="GRASS"/>
 <tile id="534" type="GRASS"/>
 <tile id="535" type="GRASS"/>
 <tile id="536" type="GRASS"/>
 <tile id="537" type="GRASS"/>
 <tile id="552" type="GRASS"/>
 <tile id="553" type="GRASS"/>
 <tile id="554" type="GRASS"/>
 <tile id="555" type="GRASS"/>
 <tile id="556" type="GRASS"/>
 <tile id="557" type="GRASS"/>
 <tile id="558" type="GRASS"/>
 <tile id="559" type="GRASS"/>
 <tile id="560" type="GRASS"/>
 <tile id="575" type="GRASS"/>
 <tile id="576" type="GRASS"/>
 <tile id="577" type="GRASS"/>
 <tile id="578" type="GRASS"/>
 <tile id="579" type="GRASS"/>
 <tile id="580" type="GRASS"/>
 <tile id="581" type="GRASS"/>
 <tile id="582" type="GRASS"/>
 <tile id="598" type="GRASS"/>
 <tile id="599" type="GRASS"/>
 <tile id="600" type="GRASS"/>
 <tile id="601" type="GRASS"/>
 <tile id="602" type="GRASS"/>
 <tile id="603" type="GRASS"/>
 <tile id="604" type="GRASS"/>
 <tile id="605" type="GRASS"/>
 <tile id="621" type="GRASS"/>
 <tile id="622" type="GRASS"/>
 <tile id="623" type="GRASS"/>
 <tile id="624" type="GRASS"/>
 <tile id="625" type="GRASS"/>
 <tile id="626" type="GRASS"/>
 <tile id="644" type="GRASS"/>
 <tile id="645" type="GRASS"/>
 <tile id="646" type="GRASS"/>
 <tile id="647" type="GRASS"/>
 <tile id="648" type="GRASS"/>
 <tile id="649" type="GRASS"/>
</tileset>
